# docker/frontend/Dockerfile.dev
FROM vadimcastro-me-frontend-base:latest
WORKDIR /app

# Set environment variables
ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1

# Start the development server
CMD ["npm", "run", "dev"]