# docker/frontend/Dockerfile.dev
ARG PROJECT_SLUG=vpt-core
FROM ${PROJECT_SLUG}-frontend-base:latest
WORKDIR /app

# Set environment variables
ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1

# Start the development server
CMD ["npm", "run", "dev"]
