# vadimcastro.me ultra development overrides
# Use with: docker compose -f ../../vadimOS/docker/docker-compose.base.yml -f docker-compose.yml -f ../../vadimOS/docker/docker-compose.dev.ultra.yml -f docker-compose.dev.ultra.yml

services:
  # Complete override for pre-built images with corrected absolute volume paths
  frontend:
    image: vadimcastro-me-frontend-base:latest
    volumes:
      - /Users/vadimcastro/Desktop/PROJECTS/vadimcastro.me/frontend:/app
      - frontend_node_modules:/app/node_modules
      - /app/.next
    command: sh -c "npm run dev"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_ADMIN_NAME=Vadim Castro
      - NEXT_PUBLIC_ADMIN_ROLE=Administrator
      - NEXT_PUBLIC_ADMIN_INITIALS=VC
      
  api:
    image: vadimcastro-me-backend-base:latest
    volumes:
      - /Users/vadimcastro/Desktop/PROJECTS/vadimcastro.me/backend:/app
    env_file:
      - /Users/vadimcastro/Desktop/PROJECTS/vadimcastro.me/.env.development
    environment:
      - POSTGRES_DB=vadimcastrome
      - PYTHONPATH=/app
    working_dir: /app
    command: >
      sh -c '
        echo "⚡ Ultra startup - starting server directly..." &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      '