# vadimcastro.me specific overrides
# Use with: docker compose -f ../../vadimOS/docker/docker-compose.base.yml -f docker-compose.yml

services:
  # Override database name for vadimcastro.me
  db:
    environment:
      - POSTGRES_DB=vadimcastro-me
      
  # Override API database connection
  api:
    environment:
      - POSTGRES_DB=vadimcastro-me