# vadimcastro.me ultra development overrides
# Use with: docker compose -f ../../vadimOS/docker/docker-compose.base.yml -f docker-compose.yml -f ../../vadimOS/docker/docker-compose.dev.ultra.yml -f docker-compose.dev.ultra.yml

services:
  # Override for pre-built images
  frontend:
    image: vadimcastro-me-frontend-base:latest
    environment:
      - NEXT_PUBLIC_ADMIN_NAME=Vadim Castro
      - NEXT_PUBLIC_ADMIN_ROLE=Administrator
      - NEXT_PUBLIC_ADMIN_INITIALS=VC
      
  api:
    image: vadimcastro-me-backend-base:latest
    env_file:
      - /Users/vadimcastro/Desktop/PROJECTS/vadimcastro.me/.env.development
    volumes:
      - ../backend/.env:/app/.env:ro
    environment:
      - POSTGRES_DB=vadimcastro-me