# vadimcastro.me development overrides
# Use with: docker compose -f ../../vadimOS/docker/docker-compose.base.yml -f docker-compose.yml -f ../../vadimOS/docker/docker-compose.dev.yml -f docker-compose.dev.yml

services:
  frontend:
    environment:
      - NEXT_PUBLIC_ADMIN_NAME=Vadim Castro
      - NEXT_PUBLIC_ADMIN_ROLE=Administrator
      - NEXT_PUBLIC_ADMIN_INITIALS=VC
      
  api:
    env_file:
      - /Users/vadimcastro/Desktop/PROJECTS/vadimcastro.me/.env.development
    volumes:
      - ../backend/.env:/app/.env:ro