"""add analytics and project status

Revision ID: 007
Revises: 006
Create Date: 2026-03-24 14:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007'
down_revision = '006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_interactions_id'), 'analytics_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_interactions_interaction_type'), 'analytics_interactions', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_analytics_interactions_target_id'), 'analytics_interactions', ['target_id'], unique=False)
    
    op.add_column('projects', sa.Column('status', sa.String(), server_default='active', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'status')
    op.drop_index(op.f('ix_analytics_interactions_target_id'), table_name='analytics_interactions')
    op.drop_index(op.f('ix_analytics_interactions_interaction_type'), table_name='analytics_interactions')
    op.drop_index(op.f('ix_analytics_interactions_id'), table_name='analytics_interactions')
    op.drop_table('analytics_interactions')
    # ### end Alembic commands ###
