"""Add icon_url to projects

Revision ID: 8a80393bd3f2
Revises: c08583035c3e
Create Date: 2026-03-24 22:43:37.810147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a80393bd3f2'
down_revision: Union[str, None] = 'c08583035c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('icon_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'icon_url')
    # ### end Alembic commands ###
