"""Add github_url and tech_implementation to projects

Revision ID: c08583035c3e
Revises: 007
Create Date: 2026-03-24 22:09:25.868542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c08583035c3e'
down_revision: Union[str, None] = '007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('github_url', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('technical_implementation', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'technical_implementation')
    op.drop_column('projects', 'github_url')
    # ### end Alembic commands ###
